#!/usr/bin/env python3

import argparse
import traceback
import pickle
from typing import Optional

from ploxb.Scanner import Scanner
from ploxb.Compiler import Compiler
from ploxb.x86BytecodeTranslator import x86BytecodeTranslator
from ploxb.VM import VM

from prompt_toolkit import PromptSession
from prompt_toolkit.history import FileHistory
from pathlib import Path
from platformdirs import user_data_dir
from termcolor import colored


class Ploxb:
    def __init__(self):
        self.vm = VM()

    def run_bytecode(self, bytecode_file: str, debug: bool = False) -> None:
        """Load and execute bytecode from a file"""
        try:
            with open(bytecode_file, "rb") as f:
                main_function = pickle.load(f)
        except Exception as e:
            print(colored(f"Error loading bytecode file: {e}", "light_red"))
            return

        if debug:
            main_function.dis()
            print()

        try:
            self.vm.run(main_function, debug)
        except Exception as e:
            if debug:
                traceback.print_exc()
            self.vm.stack = []
            self.vm.frames = []
            self.vm.open_upvalues = []
            print(colored(f"Runtime Error: {e}", "light_red"))
            return

    def run(
        self,
        source: str,
        debug: bool = False,
        x86_output_file: Optional[str] = None,
        bytecode_output_file: Optional[str] = None,
    ) -> None:
        scanner = Scanner(source)
        try:
            tokens = scanner.scan()
        except Exception as e:
            if debug:
                traceback.print_exc()
            print(colored(f"Scanning Error: {e}", "light_red"))
            return None

        compiler = Compiler(tokens)
        try:
            main_function = compiler.compile()
        except Exception as e:
            if debug:
                traceback.print_exc()
            print(colored(f"Compilation Error: {e}", "light_red"))
            return None

        if not main_function:
            return

        if bytecode_output_file is not None:
            try:
                with open(bytecode_output_file, "wb") as f:
                    pickle.dump(main_function, f)
                print(
                    colored(
                        f"✓ Generated bytecode: {bytecode_output_file}", "light_green"
                    )
                )
            except Exception as e:
                if debug:
                    traceback.print_exc()
                print(colored(f"Error writing bytecode file: {e}", "light_red"))
            return

        if x86_output_file is not None:
            translator = x86BytecodeTranslator(main_function)
            try:
                assembly = translator.translate()
            except Exception as e:
                if debug:
                    traceback.print_exc()
                print(colored(f"x86 Translation Error: {e}", "light_red"))
                return None

            try:
                with open(x86_output_file, "w") as f:
                    f.write(assembly)
                print(
                    colored(f"✓ Generated assembly: {x86_output_file}", "light_green")
                )
            except Exception as e:
                if debug:
                    traceback.print_exc()
                print(colored(f"Error writing assembly file: {e}", "light_red"))
            return

        if debug:
            main_function.dis()
            print()

        try:
            self.vm.run(main_function, debug)
        except Exception as e:
            if debug:
                traceback.print_exc()
            self.vm.stack = []
            self.vm.frames = []
            self.vm.open_upvalues = []
            print(colored(f"Runtime Error: {e}", "light_red"))
            return

    def main(self):
        parser = argparse.ArgumentParser(
            prog="ploxb",
            description="Lox Bytecode compiler in Python",
        )
        parser.add_argument("--debug", action="store_true", help="Enable debug mode")

        mode_group = parser.add_mutually_exclusive_group()
        mode_group.add_argument(
            "--to-x86",
            type=str,
            metavar="OUTPUT",
            help="Compile to x86-64 assembly and save to OUTPUT file",
        )
        mode_group.add_argument(
            "--to-bytecode",
            type=str,
            metavar="OUTPUT",
            help="Compile to bytecode and save to OUTPUT file",
        )
        mode_group.add_argument(
            "--run-bytecode",
            type=str,
            metavar="INPUT",
            help="Load and execute bytecode from INPUT file",
        )
        parser.add_argument(
            "file", nargs="?", help="Interpret a file instead of running the REPL"
        )

        args = parser.parse_args()

        if args.run_bytecode:
            self.run_bytecode(args.run_bytecode, args.debug)
            return

        if args.file:
            with open(args.file, "r") as file:
                source = file.read()
                self.run(
                    source,
                    args.debug,
                    args.to_x86,
                    args.to_bytecode,
                )
                return

        while True:
            history_file = (
                Path(user_data_dir("ploxb", ensure_exists=True)) / ".ploxb_history"
            )
            prompt_session: PromptSession[str] = PromptSession(
                history=FileHistory(history_file)
            )

            try:
                source = prompt_session.prompt("> ")
            except (EOFError, KeyboardInterrupt):
                break

            self.run(source, args.debug)


def main():
    ploxb = Ploxb()
    ploxb.main()


if __name__ == "__main__":
    main()
